# generated by datamodel-codegen:
#   filename:  site-host.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Arg(RootModel[str]):
    root: str = Field(..., max_length=4096)


class SiteLocalServer(BaseModel):
    """
    A local MCP server a machine administrator added at the machine
    (`eugene-plexus-agent site server add`, elevated). Kept in the install's
    protected configuration, which the host's own account cannot write, and
    handed to the host when it starts (§6.2).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="Its id on this site. An id beginning `files` is refused; `files` is Eugene's own file server.",
        pattern='^[a-z][a-z0-9-]{0,39}$',
    )
    name: str = Field(..., max_length=80, min_length=1)
    command: str = Field(
        ..., description="The program's absolute path.", max_length=4096, min_length=1
    )
    args: list[Arg] | None = Field(None, max_length=64)
    env: dict[str, str] | None = None
    sha256: str = Field(
        ...,
        description="The program file's SHA-256 when it was added. A program that changed since is not run.",
        pattern='^[a-f0-9]{64}$',
    )
    system: bool | None = Field(
        False, description='Marked as able to alter the operating system (J9).'
    )
    consentedAt: AwareDatetime | None = Field(
        None,
        description='When an administrator, proven elevated at the machine, consented to\nthis system server. A `system` server without it is never enabled.\n',
    )


class SiteHostHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ready: bool
    reason: str | None = Field(None, max_length=1024)


class SiteHostMode(StrEnum):
    site = 'site'
    node = 'node'


class SiteHostProtocol(StrEnum):
    """
    What a machine's host speaks to the root, through its agent. The only value is MCP's 2026-07-28 revision.
    """

    mcp_2026_07_28 = 'mcp-2026-07-28'


class SiteFolderPerson(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description="A person's id. Never `operator`; Eugene's owner reaches a site only through `ownerInDevMode`.",
        max_length=64,
        min_length=1,
    )
    writable: bool = Field(
        ...,
        description='The person may change files in it: a standing pre-approval for\n`write_text` (J6b). Otherwise they may list and read.\n',
    )


class SiteServerKind(StrEnum):
    """
    `files`: Eugene's own file server, one per machine, its tools taking a `folder` argument (J6g). `local`: a server a machine administrator added at the machine.
    """

    files = 'files'
    local = 'local'


class SiteTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=128, min_length=1)
    title: str | None = Field(None, max_length=256)
    description: str | None = Field(None, max_length=2048)
    readOnly: bool = Field(
        ...,
        description='The server marks the tool as changing nothing (`readOnlyHint`).',
    )
    destructive: bool = Field(
        ...,
        description="Whether the site treats the tool as able to change or delete\nsomething. True unless the server marks it read-only, or marks it\n`destructiveHint: false`. MCP's own default, so an unmarked tool is\ndestructive. A destructive tool runs only under a standing\npre-approval (J6b).\n",
    )


class SiteToolGrant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=128, min_length=1)
    standing: bool | None = Field(
        False,
        description="A standing pre-approval: the person may use this destructive tool\nwithout the site's owner approving each call. Required for a\ndestructive tool, which is otherwise refused: approving each call at\nthe machine waits for the held channel (J6b).\n",
    )


class McpJsonRpc(StrEnum):
    field_2_0 = '2.0'


class McpMethod(StrEnum):
    server_discover = 'server/discover'
    tools_list = 'tools/list'
    tools_call = 'tools/call'


class SiteGrantHint(BaseModel):
    """
    One of the root's own folder grants, carried with a call in a list
    (`grants`): on an ordinary node, all of the person's grants there, the
    root's grant being final (J6d); on a job site, Eugene's owner's dev-mode
    grants, which the site honours only if its owner opted in (J6e). The
    host checks the folder a call names against them.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    folderId: str = Field(..., max_length=64, min_length=1)
    name: str = Field(
        ...,
        description="The folder's name on this machine, as the `folder` argument takes it. The root makes it unique; a folder that shares a name with an earlier one reads `Name (2)`.",
        max_length=96,
        min_length=1,
    )
    path: str = Field(..., max_length=4096, min_length=1)
    identity: str = Field(..., max_length=256, min_length=1)
    writable: bool


class InstallModeName(StrEnum):
    production = 'production'
    dev = 'dev'


class SiteManageAction(StrEnum):
    """
    - `folder.inspect` (`SiteFolderInspect`), node mode, from `operator`:
      check a folder can be opened, and return its full path and
      identity for the root to register.
    - `folder.add` (`SiteFolderAdd`), site mode, from the owner:
      register a folder here, under a name no other folder here has. It
      returns `SiteFolder`, with nobody on its list.
    - `folder.remove` (`SiteFolderRemove`), site mode, from the owner.
    - `folder.people` (`SiteFolderPeople`), site mode, from the owner:
      who may use one folder, and who may change files in it, replacing
      what was there. It returns `SiteFolder`.
    - `access.set` (`SiteAccessSet`), site mode, from the owner: who may
      use one local server, and which tools, replacing what was there.
    - `server.enable` (`SiteServerEnable`), site mode, from the owner: a
      local server on or off.
    - `settings.set` (`SiteSettings`), site mode, from the owner.
    - `audit.read` (`SiteAuditRead`), site mode, from the owner: the
      newest entries of the site's audit log.

    """

    folder_inspect = 'folder.inspect'
    folder_add = 'folder.add'
    folder_remove = 'folder.remove'
    folder_people = 'folder.people'
    access_set = 'access.set'
    server_enable = 'server.enable'
    settings_set = 'settings.set'
    audit_read = 'audit.read'


class SiteManage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., max_length=128, min_length=1)
    expiresAt: float
    subject: str = Field(..., max_length=64, min_length=1)
    action: SiteManageAction
    arguments: dict[str, Any] = Field(
        ...,
        description="The action's arguments; see `SiteManageAction` for each one's schema.",
    )


class SiteFolderInspect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., max_length=4096, min_length=1)


class SiteFolderInspected(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., max_length=4096, min_length=1)
    identity: str = Field(..., max_length=256, min_length=1)


class SiteFolderAdd(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=80, min_length=1)
    path: str = Field(..., max_length=4096, min_length=1)
    writable: bool | None = False


class SiteFolderRemove(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')


class SiteFolderPeople(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')
    people: list[SiteFolderPerson] = Field(
        ...,
        description="Each person once. `writable` cannot exceed the folder's.",
        max_length=256,
    )


class SitePersonTools(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., max_length=64, min_length=1)
    tools: list[SiteToolGrant] = Field(..., max_length=64)


class SiteAccessSet(BaseModel):
    """
    A local server's list. Eugene's file server is granted per folder (`folder.people`).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    people: list[SitePersonTools] = Field(..., max_length=256)


class SiteServerEnable(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    enabled: bool


class SiteSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ownerInDevMode: bool


class SiteAuditRead(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: int | None = Field(50, ge=1, le=200)


class SiteAnswerStatus(StrEnum):
    """
    `done`: the site answered (an MCP error or a tool's own failure is still
    `done`, inside `response`). `failed`: the site refused or could not run
    it, and `message` says why in the site's words; nothing ran. `uncertain`:
    a tool call started and its end could not be established; it may have
    acted.

    """

    done = 'done'
    failed = 'failed'
    uncertain = 'uncertain'


class SiteAuditDecision(StrEnum):
    allowed = 'allowed'
    refused = 'refused'


class SiteAuditKind(StrEnum):
    mcp = 'mcp'
    manage = 'manage'


class McpResponse(BaseModel):
    """
    The JSON-RPC response to an `McpRequest`, exactly as the site's server
    produced it after the site's policy filtered it: `result` or `error`.

    """

    jsonrpc: McpJsonRpc
    id: str | int | None = None
    result: dict[str, Any] | None = None
    error: dict[str, Any] | None = None


class SiteLocalServerList(BaseModel):
    """
    The file of local servers (`site-servers.yaml`) the agent keeps in its protected configuration.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    servers: list[SiteLocalServer] = Field(..., max_length=32)


class SiteAccess(BaseModel):
    """
    Who may use which tools of one local server. Eugene's file server is
    granted per folder instead (`SiteFolder.people`, J6g).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description="A person's id. Never `operator`; Eugene's owner reaches a site only through `ownerInDevMode`.",
        max_length=64,
        min_length=1,
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    tools: list[SiteToolGrant] = Field(..., max_length=64)


class SiteFolder(BaseModel):
    """
    A folder registered on the machine. Eugene's file server offers it to
    the people on its list, by its name, as its tools' `folder` argument
    (J6g).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')
    name: str = Field(
        ...,
        description='Unique on the machine, and the value of the `folder` argument. A\nfolder that shares a name with one registered before it is shown,\nand taken, as `Name (2)`, `Name (3)` and so on.\n',
        max_length=96,
        min_length=1,
    )
    path: str = Field(..., max_length=4096, min_length=1)
    identity: str = Field(
        ...,
        description="The folder's identity on its file system, as the site recorded it. A dev-mode grant names it (`SiteGrantHint`).",
        max_length=256,
        min_length=1,
    )
    writable: bool = Field(
        ...,
        description="Whether anyone may change files in it at all. A person's `writable` cannot exceed it.",
    )
    people: list[SiteFolderPerson] = Field(
        ...,
        description="Who may use it, the site's owner included (J11). Nobody is on it until the owner says so.",
        max_length=256,
    )


class SiteServer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    name: str = Field(..., max_length=80, min_length=1)
    kind: SiteServerKind
    system: bool = Field(
        ...,
        description="Marked as able to alter the machine's operating system. It cannot be\nenabled without an administrator's consent recorded at the machine\n(J9).\n",
    )
    enabled: bool = Field(
        ...,
        description="Whether it is on. Eugene's file server is on while a folder is registered; a local server is on once the site's owner turns it on.",
    )
    available: bool = Field(..., description='Whether it can run now.')
    reason: str | None = Field(
        None, description='Why it cannot run, in plain words.', max_length=1024
    )
    tools: list[SiteTool] = Field(..., max_length=64)


class McpRequest(BaseModel):
    """
    One MCP request of the 2026-07-28 revision: `server/discover`,
    `tools/list` or `tools/call`. `params._meta` carries
    `io.modelcontextprotocol/protocolVersion` (`2026-07-28`) and may carry the
    client's info and capabilities. Nothing else crosses: no notifications, no
    server-initiated requests, no other methods.

    """

    jsonrpc: McpJsonRpc
    id: str | int = Field(
        ..., description='A JSON-RPC id. The site answers with the same one.'
    )
    method: McpMethod
    params: dict[str, Any] | None = None


class SiteAuditEntry(BaseModel):
    """
    One line of the site's own audit log, kept on the machine and read by
    its owner (J8). It records who asked for what and what the site decided,
    never a file's contents or a tool's result.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    at: AwareDatetime
    subject: str = Field(..., max_length=64)
    kind: SiteAuditKind
    server: str | None = Field(None, max_length=40)
    method: str | None = Field(None, max_length=64)
    tool: str | None = Field(None, max_length=128)
    action: str | None = Field(None, max_length=64)
    arguments: str | None = Field(
        None,
        description="The call's arguments as JSON, cut at 1,024 characters, with a write's text left out.",
        max_length=1024,
    )
    decision: SiteAuditDecision
    outcome: SiteAnswerStatus | None = None
    reason: str | None = Field(None, max_length=1024)


class SiteAnswer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: SiteAnswerStatus
    message: str | None = Field(None, max_length=1024)
    response: McpResponse | None = Field(
        None, description='For an MCP request answered, the JSON-RPC response.'
    )
    result: dict[str, Any] | None = Field(
        None, description='For a management action, its result.'
    )


class SiteSummary(BaseModel):
    """
    What a job site holds, as the site itself reports it in each poll. The
    root keeps it as a cache: it answers Workbench's listings from it, and
    the site checks every call against its own copy again (rule 2 of §3.3).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    owner: str = Field(
        ...,
        description='The person the site pinned as its owner at its join.',
        max_length=64,
        min_length=1,
    )
    ownerInDevMode: bool = Field(
        ...,
        description="The site's owner lets Eugene's owner in while Eugene is in dev mode (J6e).",
    )
    folders: list[SiteFolder] = Field(..., max_length=64)
    servers: list[SiteServer] = Field(..., max_length=96)
    access: list[SiteAccess] = Field(
        ...,
        description="Who may use the local servers' tools. Folders carry their own people.",
        max_length=2048,
    )


class SiteCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="The root's operation id; used once.",
        max_length=128,
        min_length=1,
    )
    expiresAt: float = Field(..., description='Unix seconds. At most 30 s ahead.')
    subject: str = Field(
        ...,
        description="Who asked, as the root says (a person's id, or `operator` for Eugene's owner).",
        max_length=64,
        min_length=1,
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    request: McpRequest
    grants: list[SiteGrantHint] | None = Field(
        None,
        description="The person's grants on this machine, on a node; Eugene's owner's dev-mode grants, on a site. Empty otherwise.",
        max_length=64,
    )
    installMode: InstallModeName


class SiteAuditPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entries: list[SiteAuditEntry] = Field(..., max_length=200)


class SiteHostReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: SiteHostProtocol
    version: str = Field(..., max_length=64)
    mode: SiteHostMode
    ready: bool
    reason: str | None = Field(None, max_length=1024)
    site: SiteSummary | None = Field(None, description='In `site` mode only.')
