# generated by datamodel-codegen:
#   filename:  site-host.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Arg(RootModel[str]):
    root: str = Field(..., max_length=4096)


class SiteLocalServer(BaseModel):
    """
    A local MCP server a machine administrator added at the machine
    (`eugene-plexus-agent site server add`, elevated). Kept in the install's
    protected configuration, which neither the site host nor a worker can
    write (remote-nodes.md §6.2). It runs in the worker of whoever calls it,
    as that person, or as the site's owner for someone with no link (J27).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="Its id on this site. An id beginning `files` is refused; `files` is Eugene's own file server.",
        pattern='^[a-z][a-z0-9-]{0,39}$',
    )
    name: str = Field(..., max_length=80, min_length=1)
    command: str = Field(
        ..., description="The program's absolute path.", max_length=4096, min_length=1
    )
    args: list[Arg] | None = Field(None, max_length=64)
    env: dict[str, str] | None = None
    sha256: str = Field(
        ...,
        description="The program file's SHA-256 when it was added. A program that changed since is not run.",
        pattern='^[a-f0-9]{64}$',
    )
    system: bool | None = Field(
        False, description='Marked as able to alter the operating system (J9).'
    )
    consentedAt: AwareDatetime | None = Field(
        None,
        description='When an administrator, proven elevated at the machine, consented to\nthis system server. A `system` server without it is never enabled.\n',
    )


class SiteOwnerProof(BaseModel):
    """
    The person a site invitation names, confirming the join at the machine
    with their own password (remote-nodes.md §3.3, rule 1). Checked after
    the join token, rate-limited as a sign-in is, and never stored: the root
    records the site's owner from it, so ownership comes from presence plus
    the person's own credential.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=256, min_length=1)
    password: str = Field(..., max_length=1024, min_length=1)


class SiteHostProtocol(StrEnum):
    """
    What a site host speaks to the root. The only value is MCP's 2026-07-28 revision.
    """

    mcp_2026_07_28 = 'mcp-2026-07-28'


class SitePersonLink(BaseModel):
    """
    One person linked to an OS account on a site's machine, as the site reports it.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ..., description="The person's id.", max_length=64, min_length=1
    )
    accountName: str = Field(
        ...,
        description='The OS account, for display, e.g. `AMISH_STATION\\jessie` or `jessie`.',
        max_length=256,
        min_length=1,
    )
    available: bool = Field(
        ..., description='Their worker is connected, so their calls can run now.'
    )
    reason: str | None = Field(
        None,
        description='Why not, when it is not, e.g. that they are not signed in on a Windows machine (J25).',
        max_length=1024,
    )
    keys: int | None = Field(
        None,
        description='How many keys this person has pinned at the machine (J14a). Absent from a site older than J14a.',
        ge=0,
        le=8,
    )


class SiteFolderPerson(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description="A person's id. Never `operator`; Eugene's owner reaches a site only through `ownerInDevMode`.",
        max_length=64,
        min_length=1,
    )
    writable: bool = Field(
        ...,
        description='The person may change files in it: a standing pre-approval for\n`write_text` (J6b). Otherwise they may list and read.\n',
    )


class SiteServerId(RootModel[str]):
    root: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )


class SiteServerKind(StrEnum):
    """
    `files`: Eugene's own file server, one per machine, its tools taking a `folder` argument (J6g). `local`: a server a machine administrator added at the machine.
    """

    files = 'files'
    local = 'local'


class SiteSigningState(StrEnum):
    """
    `unsigned`: the site's owner has no key pinned at the machine. Its rules
    are trusted to the root, and no tool runs there as anyone (J48).
    `unconfirmed`: the owner has a key, but has not approved the site's
    current rules with it (J52); no tool runs. `signed`: every rule the site
    holds was approved with its owner's key, at the machine; tools run.

    """

    unsigned = 'unsigned'
    unconfirmed = 'unconfirmed'
    signed = 'signed'


class SiteTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=128, min_length=1)
    title: str | None = Field(None, max_length=256)
    description: str | None = Field(None, max_length=2048)
    readOnly: bool = Field(
        ...,
        description='The server marks the tool as changing nothing (`readOnlyHint`).',
    )
    destructive: bool = Field(
        ...,
        description="Whether the site treats the tool as able to change or delete\nsomething. True unless the server marks it read-only, or marks it\n`destructiveHint: false`. MCP's own default, so an unmarked tool is\ndestructive. A destructive tool runs only under a standing\npre-approval (J6b).\n",
    )


class SiteToolGrant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=128, min_length=1)
    standing: bool | None = Field(
        False,
        description="A standing pre-approval: the person may use this destructive tool\nwithout the site's owner approving each call. Required for a\ndestructive tool, which is otherwise refused: approving each call at\nthe machine waits for the held channel (J6b).\n",
    )


class SitePollAnswer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation: str | None = Field(
        ...,
        description='The id of an operation waiting for this site to claim, or null when the long poll ended with none.',
    )


class InstallModeName(StrEnum):
    """
    The install's mode (J13, J18). In `dev`, Eugene's owner sees all tool information; in `production`, owners are restricted.
    """

    production = 'production'
    dev = 'dev'


class SiteGrantHint(BaseModel):
    """
    One of Eugene's owner's dev-mode folder grants on a site (J13b), carried
    with a call in a list (`grants`). The site honours them only if its
    owner opted in there (J6e) and Eugene is in dev mode. The host checks
    the folder a call names against them.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    folderId: str = Field(..., max_length=64, min_length=1)
    name: str = Field(
        ...,
        description="The folder's name on this machine, as the `folder` argument takes it. The root makes it unique; a folder that shares a name with an earlier one reads `Name (2)`.",
        max_length=96,
        min_length=1,
    )
    path: str = Field(..., max_length=4096, min_length=1)
    identity: str = Field(..., max_length=256, min_length=1)
    writable: bool


class SiteOperationKind(StrEnum):
    """
    `mcp`: one MCP request to one of the site's servers. `manage`: one of the site host's management actions (`SiteManageAction`, site-host.yaml).
    """

    mcp = 'mcp'
    manage = 'manage'


class McpJsonRpc(StrEnum):
    field_2_0 = '2.0'


class McpMethod(StrEnum):
    server_discover = 'server/discover'
    tools_list = 'tools/list'
    tools_call = 'tools/call'


class McpResponse(BaseModel):
    """
    The JSON-RPC response to an `McpRequest`, exactly as the site's server
    produced it after the site's policy filtered it: `result` or `error`.

    """

    jsonrpc: McpJsonRpc
    id: str | int | None = None
    result: dict[str, Any] | None = None
    error: dict[str, Any] | None = None


class SiteAnswerStatus(StrEnum):
    """
    `done`: the site answered (an MCP error or a tool's own failure is still
    `done`, inside `response`). `failed`: the site refused or could not run
    it, and `message` says why in the site's words; nothing ran. `uncertain`:
    a tool call started and its end could not be established; it may have
    acted. `held` (J14a, J50): a change that gives access, from a person who
    has a key pinned at the machine; the site keeps it until they approve it
    there with that key, and `message` says where. Nothing changed yet.

    """

    done = 'done'
    failed = 'failed'
    uncertain = 'uncertain'
    held = 'held'


class SitePersonKeyAlg(StrEnum):
    """
    `Ed25519`: a raw 32-byte public key and a 64-byte signature. `ES256`:
    ECDSA on P-256 with SHA-256, for a browser without Ed25519: an
    uncompressed 65-byte public point and a 64-byte `r||s` signature, as
    WebCrypto gives it.

    """

    Ed25519 = 'Ed25519'
    ES256 = 'ES256'


class SitePersonCheckRequest(BaseModel):
    """
    A person's Eugene sign-in, typed at the machine to link them there (J36).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ..., description='How the person signs in.', max_length=256, min_length=1
    )
    password: str = Field(..., max_length=1024, min_length=1)


class SitePersonCheck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ..., description="The person's id.", max_length=64, min_length=1
    )
    name: str = Field(..., max_length=256)


class SiteHostHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ready: bool
    reason: str | None = Field(None, max_length=1024)
    site: str | None = Field(None, description="This site's id, once it has joined.")
    lastContactAt: AwareDatetime | None = Field(
        None, description="When the root last answered this site's poll."
    )


class SiteManageAction(StrEnum):
    """
    Each is taken from the owner this site recorded at its join, and from
    nobody else, Eugene's owner included (J6b).
    - `folder.add` (`SiteFolderAdd`):
      register a folder here, under a name no other folder here has. It
      returns `SiteFolder`, with nobody on its list.
    - `folder.remove` (`SiteFolderRemove`).
    - `folder.people` (`SiteFolderPeople`):
      who may use one folder, and who may change files in it, replacing
      what was there. It returns `SiteFolder`.
    - `access.set` (`SiteAccessSet`): who may
      use one local server, and which tools, replacing what was there.
    - `server.enable` (`SiteServerEnable`): a
      local server on or off.
    - `settings.set` (`SiteSettings`).
    - `audit.read` (`SiteAuditRead`): the
      newest entries of the site's audit log.

    """

    folder_add = 'folder.add'
    folder_remove = 'folder.remove'
    folder_people = 'folder.people'
    access_set = 'access.set'
    server_enable = 'server.enable'
    settings_set = 'settings.set'
    audit_read = 'audit.read'


class SiteManage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., max_length=128, min_length=1)
    expiresAt: float
    subject: str = Field(..., max_length=64, min_length=1)
    action: SiteManageAction
    arguments: dict[str, Any] = Field(
        ...,
        description="The action's arguments; see `SiteManageAction` for each one's schema.",
    )
    names: dict[str, Any] | None = Field(
        None,
        description='How the root names the people the arguments name (`SiteOperation.names`). Display only (J54).',
    )


class SiteEditEnvelope(BaseModel):
    """
    What a person's key signs to approve one change (J14a,
    `person-held-keys.md` §12.2). The site host builds it and gives it to
    the page as canonical JSON (keys sorted, no spaces, UTF-8); the page
    signs those bytes as given, and the site checks them against what it
    holds. `typ` and `v` keep the signature from meaning anything else.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Literal['eugene-plexus/site-edit']
    v: Literal[1]
    site: str = Field(
        ...,
        description="A site's id: random, given by the root at enrollment, and fixed for\nthat enrollment. A machine that joins again gets a new one. Never a\nmachine's name, which is only its `label`.\n",
        pattern='^s-[a-z2-7]{26}$',
    )
    enrolledAt: AwareDatetime
    person: str = Field(..., max_length=64, min_length=1)
    key: str = Field(..., pattern='^[a-f0-9]{32}$')
    act: str = Field(
        ...,
        description='A `SiteManageAction` that changes something, or `rules.confirm` (J52), whose `args` are `{"digest"}`, the SHA-256 of the site\'s whole policy.',
    )
    args: dict[str, Any]
    seq: int = Field(
        ..., description='Greater than the last this person approved here.', ge=1
    )
    iat: int = Field(..., description='Unix seconds.')


class Word(RootModel[str]):
    root: str = Field(..., max_length=1024)


class SiteHeldEdit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-z0-9]{1,32}$')
    action: str = Field(..., max_length=64)
    words: list[Word] = Field(
        ...,
        description="The change in the site host's own words, line by line, as the page shows it.",
        max_length=600,
    )
    heldAt: AwareDatetime | None
    expiresAt: AwareDatetime | None = Field(
        None, description='When the site drops it unapproved.'
    )
    envelope: str | None = Field(
        None, description='With `key`, the canonical `SiteEditEnvelope` to sign.'
    )


class Key(RootModel[str]):
    root: str = Field(..., pattern='^[a-f0-9]{32}$')


class SiteHeldList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., max_length=64)
    keys: list[Key] = Field(
        ..., description='The ids of the keys pinned to this person.', max_length=8
    )
    state: SiteSigningState | None = None
    items: list[SiteHeldEdit] = Field(..., max_length=64)


class SiteApproval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description="The person the starter's page serves.",
        max_length=64,
        min_length=1,
    )
    envelope: str = Field(
        ...,
        description='The canonical `SiteEditEnvelope`, exactly as listed.',
        max_length=262144,
        min_length=2,
    )
    key: str = Field(..., pattern='^[a-f0-9]{32}$')
    signature: str = Field(
        ...,
        description="Base64 of the signature over the envelope's UTF-8 bytes.",
        max_length=256,
        min_length=1,
    )


class SiteHeldReject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., max_length=64, min_length=1)


class SiteFolderAdd(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=80, min_length=1)
    path: str = Field(..., max_length=4096, min_length=1)
    writable: bool | None = False


class SiteFolderRemove(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')


class SiteFolderPeople(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')
    people: list[SiteFolderPerson] = Field(
        ...,
        description="Each person once. `writable` cannot exceed the folder's.",
        max_length=256,
    )


class SitePersonTools(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., max_length=64, min_length=1)
    tools: list[SiteToolGrant] = Field(..., max_length=64)


class SiteAccessSet(BaseModel):
    """
    A local server's list. Eugene's file server is granted per folder (`folder.people`).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    people: list[SitePersonTools] = Field(..., max_length=256)


class SiteServerEnable(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    enabled: bool


class SiteSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ownerInDevMode: bool


class SiteAuditRead(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: int | None = Field(50, ge=1, le=200)


class SiteAuditDecision(StrEnum):
    allowed = 'allowed'
    refused = 'refused'


class SiteAuditKind(StrEnum):
    mcp = 'mcp'
    manage = 'manage'


class SiteAnswer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: SiteAnswerStatus
    message: str | None = Field(None, max_length=1024)
    response: McpResponse | None = Field(
        None, description='For an MCP request answered, the JSON-RPC response.'
    )
    result: dict[str, Any] | None = Field(
        None, description='For a management action, its result.'
    )


class SiteLocalServerList(BaseModel):
    """
    The local-server list (`servers.yaml`), beside the links in the
    install's administrator-only place (§3.2). An administrator writes it at
    the machine. The site host and each worker read it directly and cannot
    write it, so the site host cannot name a program for a worker to run.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    servers: list[SiteLocalServer] = Field(..., max_length=32)


class SiteEnrollmentRequest(BaseModel):
    """
    What a site host sends to join (`POST /v1/sites/enroll`). It generated
    its token key first and sends only the public half; no private key
    leaves the machine (J23).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    token: str = Field(
        ...,
        description="The site invitation's join token.",
        max_length=4096,
        min_length=1,
    )
    label: str = Field(
        ...,
        description="What people call the site, the machine's name by default. Not unique, not an identifier.",
        max_length=63,
        min_length=1,
        pattern='^[A-Za-z0-9][A-Za-z0-9_.-]*$',
    )
    tokenPublicKey: str = Field(
        ...,
        description="Base64 of the site's raw Ed25519 token public key. Its tokens are checked against it, by the root alone; it is never in the trust bundle nodes receive.",
        max_length=64,
        min_length=40,
    )
    owner: SiteOwnerProof
    hostVersion: str | None = Field(None, max_length=64)


class SiteEnrollment(BaseModel):
    """
    The root's answer to a site's join. The site records its owner from it,
    once (J6b); no later answer changes it.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="A site's id: random, given by the root at enrollment, and fixed for\nthat enrollment. A machine that joins again gets a new one. Never a\nmachine's name, which is only its `label`.\n",
        pattern='^s-[a-z2-7]{26}$',
    )
    label: str = Field(
        ...,
        description="What people call the site, the machine's name by default. Not unique, not an identifier.",
        max_length=63,
        min_length=1,
        pattern='^[A-Za-z0-9][A-Za-z0-9_.-]*$',
    )
    owner: str = Field(
        ..., description="The owner's person id.", max_length=64, min_length=1
    )
    ownerName: str = Field(
        ..., description='How the owner signs in, for display.', max_length=256
    )
    controlPublicKey: str = Field(
        ...,
        description="Base64 of the root's raw Ed25519 identity key. A site that pinned a key at its join (J7a) checks it is this one.",
    )
    enrolledAt: AwareDatetime


class SiteAccess(BaseModel):
    """
    Who may use which tools of one local server. Eugene's file server is
    granted per folder instead (`SiteFolder.people`, J6g).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description="A person's id. Never `operator`; Eugene's owner reaches a site only through `ownerInDevMode`.",
        max_length=64,
        min_length=1,
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    tools: list[SiteToolGrant] = Field(..., max_length=64)


class SiteFolder(BaseModel):
    """
    A folder registered on the machine. Eugene's file server offers it to
    the people on its list, by its name, as its tools' `folder` argument
    (J6g).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')
    name: str = Field(
        ...,
        description='Unique on the machine, and the value of the `folder` argument. A\nfolder that shares a name with one registered before it is shown,\nand taken, as `Name (2)`, `Name (3)` and so on.\n',
        max_length=96,
        min_length=1,
    )
    path: str = Field(..., max_length=4096, min_length=1)
    identity: str = Field(
        ...,
        description="The folder's identity on its file system, as the site recorded it. A dev-mode grant names it (`SiteGrantHint`).",
        max_length=256,
        min_length=1,
    )
    writable: bool = Field(
        ...,
        description="Whether anyone may change files in it at all. A person's `writable` cannot exceed it.",
    )
    people: list[SiteFolderPerson] = Field(
        ...,
        description="Who may use it, the site's owner included (J11). Nobody is on it until the owner says so.",
        max_length=256,
    )


class SiteServer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    name: str = Field(..., max_length=80, min_length=1)
    kind: SiteServerKind
    system: bool = Field(
        ...,
        description="Marked as able to alter the machine's operating system. It cannot be\nenabled without an administrator's consent recorded at the machine\n(J9).\n",
    )
    enabled: bool = Field(
        ...,
        description="Whether it is on. Eugene's file server is on while a folder is registered; a local server is on once the site's owner turns it on.",
    )
    available: bool = Field(..., description='Whether it can run now.')
    reason: str | None = Field(
        None, description='Why it cannot run, in plain words.', max_length=1024
    )
    tools: list[SiteTool] = Field(..., max_length=64)


class SiteSigning(BaseModel):
    """
    Whether the site checks its owner's changes with the owner's own key (J14a).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    state: SiteSigningState
    held: int = Field(
        ...,
        description='Changes the site holds until their person approves them at the machine (J50).',
        ge=0,
        le=64,
    )
    approvePage: str | None = Field(
        None,
        description='Where a person adds a key and approves held changes, on the machine\nitself: a Windows service install, and a per-user install on Windows,\nLinux or macOS (J14a.2). Null where this install has no such page yet\n(a Linux system install, J14a.3).\n',
        max_length=256,
    )


class McpRequest(BaseModel):
    """
    One MCP request of the 2026-07-28 revision: `server/discover`,
    `tools/list` or `tools/call`. `params._meta` carries
    `io.modelcontextprotocol/protocolVersion` (`2026-07-28`) and
    `io.modelcontextprotocol/clientCapabilities` (the revision's envelope: the
    SDK answers a request without it with an error), and may carry the
    client's info. Nothing else crosses: no notifications, no server-initiated
    requests, no other methods.

    """

    jsonrpc: McpJsonRpc
    id: str | int = Field(
        ..., description='A JSON-RPC id. The site answers with the same one.'
    )
    method: McpMethod
    params: dict[str, Any] | None = None


class SiteResult(BaseModel):
    """
    A site's answer to an operation it claimed (`POST /v1/sites/operations/{id}/result`).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    status: SiteAnswerStatus
    message: str | None = Field(None, max_length=1024)
    result: dict[str, Any] | None = Field(
        None, description="A management action's result."
    )
    response: McpResponse | None = Field(
        None,
        description="An MCP request's JSON-RPC response, as the site's server answered it after its policy filtered it.",
    )


class SitePersonKey(BaseModel):
    """
    A person's own key (J14a, Path A). Its private half was made in the
    person's browser on the machine's loopback page and cannot leave it;
    the root never saw either half. Written to the links file by the
    machine's privileged starter, at the machine.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description='The first 16 bytes of SHA-256 over the raw public key, in hex.',
        pattern='^[a-f0-9]{32}$',
    )
    alg: SitePersonKeyAlg
    publicKey: str = Field(
        ..., description='Base64 of the raw public key.', max_length=128, min_length=1
    )
    label: str | None = Field(
        None,
        description='Where it was made, for display, e.g. "Chrome on AMISH_STATION".',
        max_length=120,
    )
    addedAt: AwareDatetime


class SiteCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="The root's operation id; used once.",
        max_length=128,
        min_length=1,
    )
    expiresAt: float = Field(..., description='Unix seconds. At most 30 s ahead.')
    subject: str = Field(
        ...,
        description="Who asked, as the root says (a person's id, or `operator` for Eugene's owner).",
        max_length=64,
        min_length=1,
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    request: McpRequest
    grants: list[SiteGrantHint] | None = Field(
        None,
        description="Eugene's owner's dev-mode grants on this site (J6e). Empty otherwise.",
        max_length=64,
    )
    installMode: InstallModeName


class SiteAuditEntry(BaseModel):
    """
    One line of the site's own audit log, kept on the machine and read by
    its owner (J8). It records who asked for what and what the site decided,
    never a file's contents or a tool's result.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    at: AwareDatetime
    subject: str = Field(..., max_length=64)
    kind: SiteAuditKind
    server: str | None = Field(None, max_length=40)
    method: str | None = Field(None, max_length=64)
    tool: str | None = Field(None, max_length=128)
    action: str | None = Field(None, max_length=64)
    arguments: str | None = Field(
        None,
        description="The call's arguments as JSON, cut at 1,024 characters, with a write's text left out.",
        max_length=1024,
    )
    decision: SiteAuditDecision
    outcome: SiteAnswerStatus | None = None
    reason: str | None = Field(None, max_length=1024)


class SiteSummary(BaseModel):
    """
    What a job site holds, as the site itself reports it in each poll. The
    root keeps it as a cache: it answers Workbench's listings from it, and
    the site checks every call against its own copy again (rule 2 of §3.3).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    owner: str = Field(
        ...,
        description='The person the site pinned as its owner at its join.',
        max_length=64,
        min_length=1,
    )
    ownerInDevMode: bool = Field(
        ...,
        description="The site's owner lets Eugene's owner in while Eugene is in dev mode (J6e).",
    )
    folders: list[SiteFolder] = Field(..., max_length=64)
    servers: list[SiteServer] = Field(..., max_length=96)
    access: list[SiteAccess] = Field(
        ...,
        description="Who may use the local servers' tools. Folders carry their own people.",
        max_length=2048,
    )
    links: list[SitePersonLink] | None = Field(
        None,
        description="The people linked to an OS account on this machine (§2.2, J27), and\nwhether each one's worker is connected now. A linked person's calls\nrun as their own account; anyone else's run in the owner's worker,\nas the owner, confined to the folder (J27).\n",
        max_length=256,
    )
    linkPage: str | None = Field(
        None,
        description="Where a person links their account, on the machine itself: the\nagent's loopback link page on a Windows service install. Null where\nlinking is the elevated one-liner (a Linux system install, J36) or\nwhere only the installing person is served (a per-user install, J38).\n",
        max_length=256,
    )
    sharing: bool | None = Field(
        None,
        description='Whether this site can serve anyone but its owner. False on macOS,\nwhich has no folder boundary yet (§2.6). Absent means true.\n',
    )
    signing: SiteSigning | None = None


class SiteOperation(BaseModel):
    """
    What a site claims (`POST /v1/sites/operations/{id}/claim`): one
    operation, bound to this site's enrollment, to be done before
    `expiresAt`. The site host refuses one whose `site` or `enrolledAt` is
    not its own, so an operation queued for an earlier enrollment never runs
    on a later one; then its policy decides (J8).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., max_length=128, min_length=1)
    expiresAt: float = Field(..., description='Unix seconds. At most 30 s ahead.')
    site: str = Field(
        ...,
        description="A site's id: random, given by the root at enrollment, and fixed for\nthat enrollment. A machine that joins again gets a new one. Never a\nmachine's name, which is only its `label`.\n",
        pattern='^s-[a-z2-7]{26}$',
    )
    enrolledAt: AwareDatetime
    subject: str = Field(
        ...,
        description="Who asked, as the root established it (a person's id, or `operator` for Eugene's owner).",
        max_length=64,
        min_length=1,
    )
    kind: SiteOperationKind
    server: SiteServerId | None = Field(
        None, description="For `mcp`, the site's server."
    )
    request: McpRequest | None = Field(None, description='For `mcp`, the request.')
    grants: list[SiteGrantHint] | None = Field(
        None,
        description="For `mcp` to the file server from Eugene's owner, their dev-mode grants (J6e). Empty otherwise.",
        max_length=64,
    )
    action: str | None = Field(None, description='For `manage`, the action.')
    arguments: dict[str, Any] | None = Field(
        None, description='For `manage`, its arguments.'
    )
    names: dict[str, Any] | None = Field(
        None,
        description="For `manage`, how the root names each person the arguments name, by\nid. Display only: a site shows them on a held change marked as the\nroot's names (J54), and decides nothing by them.\n",
    )
    installMode: InstallModeName


class SiteAccountLink(BaseModel):
    """
    One link in the links file: *this Eugene person is this OS account on
    this machine* (§2.2, J27). Made at the machine only, by the machine's
    privileged starter (the agent on a Windows service install, root on a
    Linux system install, the join on a per-user install), never by the root
    or the site host.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ..., description="The person's id.", max_length=64, min_length=1
    )
    name: str | None = Field(
        None, description='How the person signs in, for display.', max_length=256
    )
    account: str = Field(
        ...,
        description="The OS account's SID on Windows, or its uid in decimal elsewhere. Compared exactly.",
        max_length=256,
        min_length=1,
    )
    accountName: str = Field(..., max_length=256, min_length=1)
    linkedAt: AwareDatetime
    keys: list[SitePersonKey] | None = Field(
        [],
        description="The person's own keys, pinned at the machine (J14a,\n`person-held-keys.md` §4.1). The site checks every change this\nperson approves against them, never the person the root names.\n",
        max_length=8,
        validate_default=True,
    )


class SiteAuditPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entries: list[SiteAuditEntry] = Field(..., max_length=200)


class SiteReport(BaseModel):
    """
    What a site host reports in each poll (`POST /v1/sites/poll`). The root
    keeps it as a cache for listings; the site checks every call against
    its own copy again (rule 2 of remote-nodes.md §3.3).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: SiteHostProtocol
    hostVersion: str | None = Field(None, max_length=64)
    ready: bool
    reason: str | None = Field(None, max_length=1024)
    account: str | None = Field(
        None,
        description="The kind of OS account the site host itself runs in. Since 2b.2 the\nsite's tools run in each person's worker, as `SiteSummary.links`\nsays, and never in this account.\n",
        max_length=256,
    )
    site: SiteSummary | None = None


class SiteLinkFile(BaseModel):
    """
    The links file (§3.2): written by the machine's privileged starter,
    read by the site host, which cannot write it. One link per person, and
    one person per account.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    version: Literal[1]
    links: list[SiteAccountLink] = Field(..., max_length=256)
