# generated by datamodel-codegen:
#   filename:  site-host.yaml

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Arg(RootModel[str]):
    root: str = Field(..., max_length=4096)


class SiteLocalServer(BaseModel):
    """
    A local MCP server a machine administrator added at the machine
    (`eugene-plexus-agent site server add`, elevated). Kept in the install's
    protected configuration, which neither the site host nor a worker can
    write (remote-nodes.md §6.2). It runs in the worker of whoever calls it,
    as that person, or as the site's owner for someone with no link (J27).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="Its id on this site. An id beginning `files` is refused; `files` is Eugene's own file server.",
        pattern='^[a-z][a-z0-9-]{0,39}$',
    )
    name: str = Field(..., max_length=80, min_length=1)
    command: str = Field(
        ..., description="The program's absolute path.", max_length=4096, min_length=1
    )
    args: list[Arg] | None = Field(None, max_length=64)
    env: dict[str, str] | None = None
    sha256: str = Field(
        ...,
        description="The program file's SHA-256 when it was added. A program that changed since is not run.",
        pattern='^[a-f0-9]{64}$',
    )
    system: bool | None = Field(
        False, description='Marked as able to alter the operating system (J9).'
    )
    consentedAt: AwareDatetime | None = Field(
        None,
        description='When an administrator, proven elevated at the machine, consented to\nthis system server. A `system` server without it is never enabled.\n',
    )


class SiteOwnerProof(BaseModel):
    """
    The person a site invitation names, confirming the join at the machine
    with their own password (remote-nodes.md §3.3, rule 1). Checked after
    the join token, rate-limited as a sign-in is, and never stored: the root
    records the site's owner from it, so ownership comes from presence plus
    the person's own credential.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=256, min_length=1)
    password: str = Field(..., max_length=1024, min_length=1)


class SiteHostProtocol(StrEnum):
    """
    What a site host speaks to the root. The only value is MCP's 2026-07-28 revision.
    """

    mcp_2026_07_28 = 'mcp-2026-07-28'


class SiteFolderPerson(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description="A person's id. Never `operator`; Eugene's owner reaches a site only through `ownerInDevMode`.",
        max_length=64,
        min_length=1,
    )
    writable: bool = Field(
        ...,
        description='The person may change files in it: a standing pre-approval for\n`write_text` and `edit_text` (J6b). Otherwise they may list, read\nand search.\n',
    )


class SiteServerId(RootModel[str]):
    root: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )


class SiteServerKind(StrEnum):
    """
    `files`: Eugene's own file server, one per machine, its tools taking a `folder` argument (J6g). `local`: a server a machine administrator added at the machine.
    """

    files = 'files'
    local = 'local'


class SiteSigningState(StrEnum):
    """
    `unsigned`: the site's owner has no key pinned at the machine. Its rules
    are trusted to the root, and no tool runs there as anyone (J48).
    `unconfirmed`: the owner has a key, but has not approved the site's
    current rules with it (J52); no tool runs. `signed`: every rule the site
    holds was approved with its owner's key, at the machine; tools run.
    Since 2b.3b (J79) the owner's state governs what the owner's rules
    govern: their own workspaces, what they shared, the local servers and
    dev mode. Each other linked person's own workspaces run under their own
    state (`SitePersonLink.signing`).

    """

    unsigned = 'unsigned'
    unconfirmed = 'unconfirmed'
    signed = 'signed'


class SiteTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=128, min_length=1)
    title: str | None = Field(None, max_length=256)
    description: str | None = Field(None, max_length=2048)
    readOnly: bool = Field(
        ...,
        description='The server marks the tool as changing nothing (`readOnlyHint`).',
    )
    destructive: bool = Field(
        ...,
        description="Whether the site treats the tool as able to change or delete\nsomething. True unless the server marks it read-only, or marks it\n`destructiveHint: false`. MCP's own default, so an unmarked tool is\ndestructive. Since 2b.3b a destructive tool is granted `ask` unless\nthe site's owner grants it `allow` (`SiteToolGrant.decision`, J78).\n",
    )


class SiteDecision(StrEnum):
    """
    What a rule says of a group of tools (J70). `allow`: runs without
    asking. `ask`: Workbench asks the person who made the call, and the site
    runs it only when the call says they approved (`SiteCall.asked`, J72);
    until person-held call signatures (J14b) the site cannot check that they
    did, and its audit log says the approval was claimed. `deny`: never
    offered, and refused.

    """

    allow = 'allow'
    ask = 'ask'
    deny = 'deny'


class SiteGrantDecision(StrEnum):
    """
    A `SiteDecision` for a tool granted by name; a tool not granted is denied.
    """

    allow = 'allow'
    ask = 'ask'


class SitePollAnswer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation: str | None = Field(
        ...,
        description='The id of an operation waiting for this site to claim, or null when the long poll ended with none.',
    )


class InstallModeName(StrEnum):
    """
    The install's mode (J13, J18). In `dev`, Eugene's owner sees all tool information; in `production`, owners are restricted.
    """

    production = 'production'
    dev = 'dev'


class SiteGrantHint(BaseModel):
    """
    One of Eugene's owner's dev-mode folder grants on a site (J13b), carried
    with a call in a list (`grants`). The site honours them only if its
    owner opted in there (J6e) and Eugene is in dev mode. The host checks
    the folder a call names against them. Only the site owner's workspaces
    can be granted. Since 2b.3b the site matches a grant by `folderId` alone
    (J76): the root keeps no paths, so a newer root sends none.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    folderId: str = Field(..., max_length=64, min_length=1)
    name: str = Field(
        ...,
        description="The folder's name on this machine, as the `folder` argument takes it. The root makes it unique; a folder that shares a name with an earlier one reads `Name (2)`.",
        max_length=96,
        min_length=1,
    )
    path: str | None = Field(
        None,
        description='From a root before 2b.3b; a newer site ignores it.',
        max_length=4096,
    )
    identity: str | None = Field(
        None,
        description='From a root before 2b.3b; a newer site ignores it.',
        max_length=256,
    )
    writable: bool


class SiteOperationKind(StrEnum):
    """
    `mcp`: one MCP request to one of the site's servers. `manage`: one of the site host's management actions (`SiteManageAction`, site-host.yaml).
    """

    mcp = 'mcp'
    manage = 'manage'


class McpJsonRpc(StrEnum):
    field_2_0 = '2.0'


class McpMethod(StrEnum):
    server_discover = 'server/discover'
    tools_list = 'tools/list'
    tools_call = 'tools/call'


class McpResponse(BaseModel):
    """
    The JSON-RPC response to an `McpRequest`, exactly as the site's server
    produced it after the site's policy filtered it: `result` or `error`.

    """

    jsonrpc: McpJsonRpc
    id: str | int | None = None
    result: dict[str, Any] | None = None
    error: dict[str, Any] | None = None


class SiteAnswerStatus(StrEnum):
    """
    `done`: the site answered (an MCP error or a tool's own failure is still
    `done`, inside `response`). `failed`: the site refused or could not run
    it, and `message` says why in the site's words; nothing ran. `uncertain`:
    a tool call started and its end could not be established; it may have
    acted. `held` (J14a, J50): a change that gives access, from a person who
    has a key pinned at the machine; the site keeps it until they approve it
    there with that key, and `message` says where. Nothing changed yet.

    """

    done = 'done'
    failed = 'failed'
    uncertain = 'uncertain'
    held = 'held'


class SitePersonKeyAlg(StrEnum):
    """
    `Ed25519`: a raw 32-byte public key and a 64-byte signature. `ES256`:
    ECDSA on P-256 with SHA-256, for a browser without Ed25519: an
    uncompressed 65-byte public point and a 64-byte `r||s` signature, as
    WebCrypto gives it.

    """

    Ed25519 = 'Ed25519'
    ES256 = 'ES256'


class SitePersonCheckRequest(BaseModel):
    """
    A person's Eugene sign-in, typed at the machine to link them there (J36).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ..., description='How the person signs in.', max_length=256, min_length=1
    )
    password: str = Field(..., max_length=1024, min_length=1)


class SitePersonCheck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ..., description="The person's id.", max_length=64, min_length=1
    )
    name: str = Field(..., max_length=256)


class SiteHostHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ready: bool
    reason: str | None = Field(None, max_length=1024)
    site: str | None = Field(None, description="This site's id, once it has joined.")
    lastContactAt: AwareDatetime | None = Field(
        None, description="When the root last answered this site's poll."
    )


class SiteManageAction(StrEnum):
    """
    Who may ask for what. Eugene's owner never (J6b).
    - **A linked person, for their own items** (2b.3b, J67; the owner
      too): `workspace.add`, `workspace.remove`, `rules.set`,
      `workspace.list`, `audit.read` (J80), and the passkey actions
      (`passkey.pair`, `held.list`, `held.approve`, `held.reject`,
      `passkey.remove`).
      A change that gives access is held until they approve it with
      their own key, and never applied on the root's word: with no key
      yet, it waits for one (J68). The site's owner keeps J52's way: with
      no key, their changes apply, and no tool runs under them until they
      approve them as a whole.
    - **The site's owner alone**, the owner this site recorded at its
      join: `workspace.people`, `access.set`, `server.enable`,
      `settings.set`, and, for a root from before 2b.3b,
      `folder.add`, `folder.remove` and `folder.people`, which act on the
      owner's workspaces.

    The actions:
    - `workspace.add` (`SiteWorkspaceAdd`, 2b.3b): add a workspace
      held by the person who asks, opened by their own worker as their
      own account, under a name none of their workspaces has. Its rules
      start as `SiteRules` says unless given. It returns
      `SiteWorkspaceDetail`, live, to that person.
    - `workspace.remove` (`SiteWorkspaceRemove`): the holder's own.
      Only takes access away, so it applies at once (J51).
    - `workspace.people` (`SiteWorkspacePeople`): whom the owner shares
      one of their own workspaces with, and each one's rules there,
      replacing what was there (J69). It returns `SiteWorkspaceDetail`.
    - `rules.set` (`SiteRulesSet`): the holder's rules in one of their
      workspaces, and its deny patterns, which bind everyone who uses it.
      A change that is nowhere looser (no decision looser, no pattern
      dropped) only takes access away and applies at once (J51).
    - `workspace.list` (`SiteWorkspaceListRequest`): the person's own
      workspaces, with their paths, rules and patterns, read live
      (J76). It returns `SiteWorkspaceList`.
    - `folder.add` (`SiteFolderAdd`):
      register a folder here, under a name no other folder here has. It
      returns `SiteFolder`, with nobody on its list. Since 2b.3b, an
      owner's workspace (for a root from before then).
    - `folder.remove` (`SiteFolderRemove`).
    - `folder.people` (`SiteFolderPeople`):
      who may use one folder, and who may change files in it, replacing
      what was there. It returns `SiteFolder`. Since 2b.3b, `writable`
      reads as `change: allow`, and not as `change: deny`; `read` is
      `allow`.
    - `access.set` (`SiteAccessSet`): who may
      use one local server, and which tools, replacing what was there.
    - `server.enable` (`SiteServerEnable`): a
      local server on or off.
    - `settings.set` (`SiteSettings`).
    - `audit.read` (`SiteAuditRead`): the
      newest entries of the site's audit log.
    - `passkey.pair` (`SitePasskeyPair`, J14a.3): pin the asking
      person's passkey, made in Workbench, if its MAC checks with the code
      this site showed them at the machine. It returns `SitePasskey`.
    - `held.list` (`SiteHeldListRequest`): what the asking person has
      waiting, as `/v1/held` lists it, with the envelopes to sign when
      `key` is one of their passkeys. It returns `SiteHeldList`.
    - `held.approve` (`SitePasskeyApproval`): apply a held change (or
      the rules as a whole), approved with a passkey assertion over its
      envelope.
    - `held.reject` (`SiteHeldRejectRequest`): drop a held change.
      Turning a change down only keeps access from being given, so the
      root may ask for it.
    - `passkey.remove` (`SitePasskeyRemove`): remove one of the asking
      person's passkeys, as at the machine; what it approved stays.
      Removing a key only takes it away (a lost phone), so the root may
      ask for it: if it was the owner's last key here, no tool runs under
      the owner's rules until they add a key and approve them (J48, J79).
    - `audit.read` (`SiteAuditRead`): since 2b.3b, the lines that belong
      to the asking person (J80), from anyone linked; the owner's include
      the local servers, sharing and settings.

    """

    folder_add = 'folder.add'
    folder_remove = 'folder.remove'
    folder_people = 'folder.people'
    access_set = 'access.set'
    server_enable = 'server.enable'
    settings_set = 'settings.set'
    audit_read = 'audit.read'
    passkey_pair = 'passkey.pair'
    held_list = 'held.list'
    held_approve = 'held.approve'
    held_reject = 'held.reject'
    passkey_remove = 'passkey.remove'
    workspace_add = 'workspace.add'
    workspace_remove = 'workspace.remove'
    workspace_people = 'workspace.people'
    rules_set = 'rules.set'
    workspace_list = 'workspace.list'


class SiteManage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., max_length=128, min_length=1)
    expiresAt: float
    subject: str = Field(..., max_length=64, min_length=1)
    action: SiteManageAction
    arguments: dict[str, Any] = Field(
        ...,
        description="The action's arguments; see `SiteManageAction` for each one's schema.",
    )
    names: dict[str, Any] | None = Field(
        None,
        description='How the root names the people the arguments name (`SiteOperation.names`). Display only (J54).',
    )


class SiteEditEnvelope(BaseModel):
    """
    What a person's key signs to approve one change (J14a,
    `person-held-keys.md` §12.2). The site host builds it and gives it to
    the page as canonical JSON (keys sorted, no spaces, UTF-8); the page
    signs those bytes as given, and the site checks them against what it
    holds. `typ` and `v` keep the signature from meaning anything else.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Literal['eugene-plexus/site-edit']
    v: Literal[1]
    site: str = Field(
        ...,
        description="A site's id: random, given by the root at enrollment, and fixed for\nthat enrollment. A machine that joins again gets a new one. Never a\nmachine's name, which is only its `label`.\n",
        pattern='^s-[a-z2-7]{26}$',
    )
    enrolledAt: AwareDatetime
    person: str = Field(..., max_length=64, min_length=1)
    key: str = Field(..., pattern='^[a-f0-9]{32}$')
    act: str = Field(
        ...,
        description='A `SiteManageAction` that changes something, or `rules.confirm` (J52), whose `args` are `{"digest"}`, the SHA-256 of the rules the person\'s key approves (since 2b.3b, that person\'s own, J67).',
    )
    args: dict[str, Any]
    seq: int = Field(
        ..., description='Greater than the last this person approved here.', ge=1
    )
    iat: int = Field(..., description='Unix seconds.')


class Word(RootModel[str]):
    root: str = Field(..., max_length=1024)


class SiteHeldEdit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-z0-9]{1,32}$')
    action: str = Field(..., max_length=64)
    words: list[Word] = Field(
        ...,
        description="The change in the site host's own words, line by line, as the page shows it.",
        max_length=600,
    )
    heldAt: AwareDatetime | None
    expiresAt: AwareDatetime | None = Field(
        None, description='When the site drops it unapproved.'
    )
    envelope: str | None = Field(
        None, description='With `key`, the canonical `SiteEditEnvelope` to sign.'
    )


class Key(RootModel[str]):
    root: str = Field(..., pattern='^[a-f0-9]{32}$')


class SitePasskeyAlgorithm(IntEnum):
    """
    A passkey's COSE algorithm: -8 EdDSA, -7 ES256, -257 RS256.
    """

    integer__8 = -8
    integer__7 = -7
    integer__257 = -257


class SiteApproval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description="The person the starter's page serves.",
        max_length=64,
        min_length=1,
    )
    envelope: str = Field(
        ...,
        description='The canonical `SiteEditEnvelope`, exactly as listed.',
        max_length=262144,
        min_length=2,
    )
    key: str = Field(..., pattern='^[a-f0-9]{32}$')
    signature: str = Field(
        ...,
        description="Base64 of the signature over the envelope's UTF-8 bytes.",
        max_length=256,
        min_length=1,
    )


class SiteHeldReject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., max_length=64, min_length=1)


class SitePasskeyCodeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description='The linked person the starter serves.',
        max_length=64,
        min_length=1,
    )


class SitePasskeyCode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., max_length=64)
    code: str = Field(
        ...,
        description='Shown at the machine and typed into Workbench; never sent to the root.',
        pattern='^[0-9A-HJKMNP-TV-Z]{5}-[0-9A-HJKMNP-TV-Z]{5}$',
    )
    expiresAt: AwareDatetime


class SitePasskeyBinding(BaseModel):
    """
    What the pairing MAC covers (J14a.3, `person-held-keys.md` §12.5).
    Workbench builds it, canonical (keys sorted, no spaces, UTF-8), and
    sends `mac` = base64url(HMAC-SHA256(k, those bytes)) without padding,
    where `k` = PBKDF2-HMAC-SHA256 over the code (its ten characters,
    upper case, without the dash) with salt
    `eugene-plexus/site-passkey:<site>:<person>`, 600000 iterations,
    32 bytes. The code is the only secret: it never leaves the machine
    and the browser, so a root that swaps the public key cannot make the
    MAC check.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Literal['eugene-plexus/site-passkey']
    v: Literal[1]
    site: str = Field(
        ...,
        description="A site's id: random, given by the root at enrollment, and fixed for\nthat enrollment. A machine that joins again gets a new one. Never a\nmachine's name, which is only its `label`.\n",
        pattern='^s-[a-z2-7]{26}$',
    )
    person: str = Field(..., max_length=64, min_length=1)
    credentialId: str = Field(..., max_length=1366)
    publicKey: str = Field(..., max_length=1100)
    alg: int
    rpId: str = Field(..., max_length=253)


class SitePasskeyPair(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    credentialId: str = Field(
        ..., max_length=1366, min_length=1, pattern='^[A-Za-z0-9_-]+$'
    )
    publicKey: str = Field(
        ...,
        description='Base64 of the public key as `SubjectPublicKeyInfo`, DER (`AuthenticatorAttestationResponse.getPublicKey()`).',
        max_length=1100,
        min_length=1,
    )
    alg: SitePasskeyAlgorithm
    rpId: str = Field(..., max_length=253, min_length=1)
    label: str | None = Field(
        None,
        description='How Workbench names it, for the lists at the machine.',
        max_length=128,
    )
    mac: str = Field(
        ..., description='See `SitePasskeyBinding`.', pattern='^[A-Za-z0-9_-]{43}$'
    )


class SiteHeldListRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str | None = Field(
        None,
        description="One of the owner's passkeys; with it, each item carries the envelope to sign.",
        pattern='^[a-f0-9]{32}$',
    )


class SitePasskeyApproval(BaseModel):
    """
    A held change approved with a passkey. The assertion's challenge is
    SHA-256 of the envelope's UTF-8 bytes. The site checks the envelope
    as it checks the loopback page's (`SiteApproval`), then the
    assertion: `clientDataJSON` is `webauthn.get` with that challenge,
    from an HTTPS origin, not cross-origin; `authenticatorData` carries
    the SHA-256 of the passkey's pinned `rpId` and says the person was
    present and verified (UP and UV); its sign count grows when the
    authenticator counts; and the signature over `authenticatorData ||
    SHA-256(clientDataJSON)` verifies with the pinned public key.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description='The held change, or `rules` for the rules as a whole (J52).',
        pattern='^[a-z0-9]{1,32}$',
    )
    envelope: str = Field(..., max_length=262144, min_length=2)
    key: str = Field(..., pattern='^[a-f0-9]{32}$')
    credentialId: str = Field(
        ..., max_length=1366, min_length=1, pattern='^[A-Za-z0-9_-]+$'
    )
    authenticatorData: str = Field(
        ..., description='Base64url.', max_length=4096, min_length=1
    )
    clientDataJSON: str = Field(
        ..., description='Base64url.', max_length=8192, min_length=1
    )
    signature: str = Field(..., description='Base64url.', max_length=1024, min_length=1)


class SiteHeldRejectRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-z0-9]{1,32}$')


class SitePasskeyRemove(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="The passkey's key id (`SitePasskey.id`).",
        pattern='^[a-f0-9]{32}$',
    )


class SiteFolderAdd(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=80, min_length=1)
    path: str = Field(..., max_length=4096, min_length=1)
    writable: bool | None = False


class SiteFolderRemove(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')


class SiteFolderPeople(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')
    people: list[SiteFolderPerson] = Field(
        ...,
        description="Each person once. `writable` cannot exceed the folder's.",
        max_length=256,
    )


class SiteDenyPattern(RootModel[str]):
    root: str = Field(
        ...,
        description="A path inside a workspace that no tool may touch (J70), in `.gitignore`'s\nsyntax without `!`: `.env`, `secrets/`, `*.pem`. It is hidden from every\ntool, for everyone who uses the workspace: listings and searches leave it\nout, and a tool that names it is refused whether or not it exists.\n",
        max_length=256,
        min_length=1,
        pattern='^[^!\\x00-\\x1f]',
    )


class SiteWorkspaceRemove(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')


class SiteWorkspaceListRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )


class SiteServerEnable(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    enabled: bool


class SiteSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ownerInDevMode: bool


class SiteAuditRead(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: int | None = Field(50, ge=1, le=200)


class SiteAuditDecision(StrEnum):
    allowed = 'allowed'
    refused = 'refused'


class SiteAuditKind(StrEnum):
    mcp = 'mcp'
    manage = 'manage'


class SiteAnswer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: SiteAnswerStatus
    message: str | None = Field(None, max_length=1024)
    response: McpResponse | None = Field(
        None, description='For an MCP request answered, the JSON-RPC response.'
    )
    result: dict[str, Any] | None = Field(
        None, description='For a management action, its result.'
    )


class SiteLocalServerList(BaseModel):
    """
    The local-server list (`servers.yaml`), beside the links in the
    install's administrator-only place (§3.2). An administrator writes it at
    the machine. The site host and each worker read it directly and cannot
    write it, so the site host cannot name a program for a worker to run.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    servers: list[SiteLocalServer] = Field(..., max_length=32)


class SiteEnrollmentRequest(BaseModel):
    """
    What a site host sends to join (`POST /v1/sites/enroll`). It generated
    its token key first and sends only the public half; no private key
    leaves the machine (J23).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    token: str = Field(
        ...,
        description="The site invitation's join token.",
        max_length=4096,
        min_length=1,
    )
    label: str = Field(
        ...,
        description="What people call the site, the machine's name by default. Not unique, not an identifier.",
        max_length=63,
        min_length=1,
        pattern='^[A-Za-z0-9][A-Za-z0-9_.-]*$',
    )
    tokenPublicKey: str = Field(
        ...,
        description="Base64 of the site's raw Ed25519 token public key. Its tokens are checked against it, by the root alone; it is never in the trust bundle nodes receive.",
        max_length=64,
        min_length=40,
    )
    owner: SiteOwnerProof
    hostVersion: str | None = Field(None, max_length=64)


class SiteEnrollment(BaseModel):
    """
    The root's answer to a site's join. The site records its owner from it,
    once (J6b); no later answer changes it.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="A site's id: random, given by the root at enrollment, and fixed for\nthat enrollment. A machine that joins again gets a new one. Never a\nmachine's name, which is only its `label`.\n",
        pattern='^s-[a-z2-7]{26}$',
    )
    label: str = Field(
        ...,
        description="What people call the site, the machine's name by default. Not unique, not an identifier.",
        max_length=63,
        min_length=1,
        pattern='^[A-Za-z0-9][A-Za-z0-9_.-]*$',
    )
    owner: str = Field(
        ..., description="The owner's person id.", max_length=64, min_length=1
    )
    ownerName: str = Field(
        ..., description='How the owner signs in, for display.', max_length=256
    )
    controlPublicKey: str = Field(
        ...,
        description="Base64 of the root's raw Ed25519 identity key. A site that pinned a key at its join (J7a) checks it is this one.",
    )
    enrolledAt: AwareDatetime


class SiteFolder(BaseModel):
    """
    A folder registered on the machine, as a site from before 2b.3b reports
    it (a newer site reports `SiteWorkspace`, without the path, J76). Eugene's
    file server offers it to the people on its list, by its name, as its
    tools' `folder` argument (J6g). Since 2b.3b the site's `folder.add`,
    `folder.remove` and `folder.people` act on its owner's workspaces, for a
    root from before then, and answer with this shape.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')
    name: str = Field(
        ...,
        description='Unique on the machine, and the value of the `folder` argument. A\nfolder that shares a name with one registered before it is shown,\nand taken, as `Name (2)`, `Name (3)` and so on.\n',
        max_length=96,
        min_length=1,
    )
    path: str = Field(..., max_length=4096, min_length=1)
    identity: str = Field(
        ...,
        description="The folder's identity on its file system, as the site recorded it. A dev-mode grant names it (`SiteGrantHint`).",
        max_length=256,
        min_length=1,
    )
    writable: bool = Field(
        ...,
        description="Whether anyone may change files in it at all. A person's `writable` cannot exceed it.",
    )
    people: list[SiteFolderPerson] = Field(
        ...,
        description="Who may use it, the site's owner included (J11). Nobody is on it until the owner says so.",
        max_length=256,
    )


class SitePersonLink(BaseModel):
    """
    One person linked to an OS account on a site's machine, as the site reports it.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ..., description="The person's id.", max_length=64, min_length=1
    )
    accountName: str = Field(
        ...,
        description='The OS account, for display, e.g. `AMISH_STATION\\jessie` or `jessie`.',
        max_length=256,
        min_length=1,
    )
    available: bool = Field(
        ..., description='Their worker is connected, so their calls can run now.'
    )
    reason: str | None = Field(
        None,
        description='Why not, when it is not, e.g. that they are not signed in on a Windows machine (J25).',
        max_length=1024,
    )
    keys: int | None = Field(
        None,
        description='How many keys this person has here, at the machine and as passkeys (J14a, J67). Absent from a site older than J14a.',
        ge=0,
        le=16,
    )
    signing: SiteSigningState | None = Field(
        None,
        description="2b.3b (J67, J68): the state of this person's own workspaces and\nrules. `unsigned`: they have no key here, so their changes wait for\none. `unconfirmed`: rules from before 2b.3b they have not approved\nwith their key (the owner's, J69). `signed`: every rule of theirs\nhere was approved with their own key. Absent from an older site.\n",
    )
    held: int | None = Field(
        None,
        description='Changes the site holds until this person approves them with their own key (2b.3b). Absent from an older site.',
        ge=0,
        le=64,
    )


class SiteServer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    name: str = Field(..., max_length=80, min_length=1)
    kind: SiteServerKind
    system: bool = Field(
        ...,
        description="Marked as able to alter the machine's operating system. It cannot be\nenabled without an administrator's consent recorded at the machine\n(J9).\n",
    )
    enabled: bool = Field(
        ...,
        description="Whether it is on. Eugene's file server is on while a folder is registered; a local server is on once the site's owner turns it on.",
    )
    available: bool = Field(..., description='Whether it can run now.')
    reason: str | None = Field(
        None, description='Why it cannot run, in plain words.', max_length=1024
    )
    tools: list[SiteTool] = Field(..., max_length=64)


class SiteSigning(BaseModel):
    """
    Whether the site checks its owner's changes with the owner's own key (J14a).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    state: SiteSigningState
    held: int = Field(
        ...,
        description="Changes the site holds until its owner approves them with their key (J50). Since 2b.3b, the owner's alone; each person's own count is on their link.",
        ge=0,
        le=64,
    )
    approvePage: str | None = Field(
        None,
        description='Where a person adds a key and approves held changes, on the machine\nitself: a Windows service install, and a per-user install on Windows,\nLinux or macOS (J14a.2). Null where this install has no such page (a\nLinux system install, whose owner pairs a passkey instead, J14a.3).\n',
        max_length=256,
    )
    passkeys: bool | None = Field(
        None,
        description="The site takes its owner's passkey from Workbench, paired with a code\nshown at the machine, and approvals made with it (J14a.3). Absent\nfrom a site older than that.\n",
    )
    people: bool | None = Field(
        None,
        description="The site keeps each linked person's own workspaces, rules and keys\n(2b.3b, J67): any linked person pairs a passkey, and adds, changes and\napproves their own. Absent from an older site, whose root offers\nthese to the owner alone.\n",
    )


class SiteRules(BaseModel):
    """
    One person's rules in one workspace, per group of tools (J70). `read`:
    `list_directory`, `read_text`, `glob` and `grep`. `change`: `write_text`
    and `edit_text`. The site stores them per tool, so commands (2b.4) add a
    group of their own. `change` cannot be looser than `deny` in a workspace
    registered read-only (`writable: false`).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    read: SiteDecision
    change: SiteDecision


class SiteToolGrant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=128, min_length=1)
    decision: SiteGrantDecision | None = Field(
        None,
        description='2b.3b (J70, J78): `allow`, the tool runs without asking; `ask`, it\nruns once the person who made the call approved it in Workbench\n(`SiteCall.asked`, J72). Absent: `allow` for a tool the site does not\ntreat as destructive, or one granted `standing`; `ask` otherwise.\nA tool not granted is denied: it is never offered.\n',
    )
    standing: bool | None = Field(
        False,
        description='From before 2b.3b: a standing pre-approval, the person may use this\ndestructive tool without being asked. Reads as `decision: allow`.\nBefore 2b.3b it was required for a destructive tool, which was\notherwise refused.\n',
    )


class SiteWorkspacePerson(BaseModel):
    """
    Someone the site's owner shares one of their own workspaces with, and
    their rules there (J69, J70). Only the owner's workspaces are shared.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description="A person's id. Never `operator`; Eugene's owner reaches a site only through `ownerInDevMode`.",
        max_length=64,
        min_length=1,
    )
    read: SiteDecision
    change: SiteDecision


class McpRequest(BaseModel):
    """
    One MCP request of the 2026-07-28 revision: `server/discover`,
    `tools/list` or `tools/call`. `params._meta` carries
    `io.modelcontextprotocol/protocolVersion` (`2026-07-28`) and
    `io.modelcontextprotocol/clientCapabilities` (the revision's envelope: the
    SDK answers a request without it with an error), and may carry the
    client's info. Nothing else crosses: no notifications, no server-initiated
    requests, no other methods.

    """

    jsonrpc: McpJsonRpc
    id: str | int = Field(
        ..., description='A JSON-RPC id. The site answers with the same one.'
    )
    method: McpMethod
    params: dict[str, Any] | None = None


class SiteResult(BaseModel):
    """
    A site's answer to an operation it claimed (`POST /v1/sites/operations/{id}/result`).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    status: SiteAnswerStatus
    message: str | None = Field(None, max_length=1024)
    result: dict[str, Any] | None = Field(
        None, description="A management action's result."
    )
    response: McpResponse | None = Field(
        None,
        description="An MCP request's JSON-RPC response, as the site's server answered it after its policy filtered it.",
    )


class SitePersonKey(BaseModel):
    """
    A person's own key (J14a, Path A). Its private half was made in the
    person's browser on the machine's loopback page and cannot leave it;
    the root never saw either half. Written to the links file by the
    machine's privileged starter, at the machine.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description='The first 16 bytes of SHA-256 over the raw public key, in hex.',
        pattern='^[a-f0-9]{32}$',
    )
    alg: SitePersonKeyAlg
    publicKey: str = Field(
        ..., description='Base64 of the raw public key.', max_length=128, min_length=1
    )
    label: str | None = Field(
        None,
        description='Where it was made, for display, e.g. "Chrome on AMISH_STATION".',
        max_length=120,
    )
    addedAt: AwareDatetime


class SiteCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="The root's operation id; used once.",
        max_length=128,
        min_length=1,
    )
    expiresAt: float = Field(..., description='Unix seconds. At most 30 s ahead.')
    subject: str = Field(
        ...,
        description="Who asked, as the root says (a person's id, or `operator` for Eugene's owner).",
        max_length=64,
        min_length=1,
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    request: McpRequest
    grants: list[SiteGrantHint] | None = Field(
        None,
        description="Eugene's owner's dev-mode grants on this site (J6e). Empty otherwise.",
        max_length=64,
    )
    installMode: InstallModeName
    asked: bool | None = Field(
        False,
        description='Workbench says the person approved this call (J72). A tool whose\nrule is `ask` is refused without it. The site cannot check it\nuntil person-held call signatures (J14b), and its audit log says\nthe approval was claimed.\n',
    )


class SitePasskey(BaseModel):
    """
    A passkey pinned to a person here (J14a.3). Its private half is in the person's own authenticator.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description='The key id an envelope names: the first 16 bytes of SHA-256 over the public key (`SubjectPublicKeyInfo`, DER), in hex.',
        pattern='^[a-f0-9]{32}$',
    )
    credentialId: str = Field(
        ...,
        description='The WebAuthn credential id, base64url without padding.',
        max_length=1366,
        min_length=1,
        pattern='^[A-Za-z0-9_-]+$',
    )
    alg: SitePasskeyAlgorithm
    rpId: str = Field(
        ...,
        description="The WebAuthn relying party id it was made for (Workbench's HTTPS name).",
        max_length=253,
        min_length=1,
    )
    label: str = Field(..., max_length=128)
    addedAt: AwareDatetime


class SitePasskeyList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., max_length=64)
    passkeys: list[SitePasskey] = Field(..., max_length=8)
    codeExpiresAt: AwareDatetime | None = Field(
        None,
        description='When the code waiting for this person expires; null when none is.',
    )


class SitePersonTools(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., max_length=64, min_length=1)
    tools: list[SiteToolGrant] = Field(..., max_length=64)


class SiteWorkspaceAdd(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description="Unique among the asking person's own workspaces.",
        max_length=80,
        min_length=1,
    )
    path: str = Field(
        ...,
        description="Opened by the asking person's own worker, as their own account.",
        max_length=4096,
        min_length=1,
    )
    writable: bool | None = Field(
        True,
        description='Whether files may be changed in it at all. When false, every `change` rule in it is `deny`.',
    )
    rules: SiteRules | None = Field(
        None,
        description="The holder's rules there. Absent, `read: allow` and `change: ask` (§2.6), or `change: deny` when not writable.",
    )
    deny: list[SiteDenyPattern] | None = Field(None, max_length=64)


class SiteWorkspacePeople(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="One of the site owner's own workspaces.",
        pattern='^[a-f0-9]{32}$',
    )
    people: list[SiteWorkspacePerson] = Field(
        ...,
        description='Each person once, never the owner. A `change` looser than `deny` needs a writable workspace.',
        max_length=256,
    )


class SiteRulesSet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="One of the asking person's own workspaces.",
        pattern='^[a-f0-9]{32}$',
    )
    rules: SiteRules
    deny: list[SiteDenyPattern] = Field(
        ..., description="Replaces the workspace's deny patterns.", max_length=64
    )


class SiteWorkspaceDetail(BaseModel):
    """
    One of a person's own workspaces as the site holds it, read live through
    the root (`workspace.list`, J76) and kept by no one else.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')
    name: str = Field(..., max_length=96, min_length=1)
    path: str = Field(..., max_length=4096, min_length=1)
    holder: str = Field(..., max_length=64, min_length=1)
    writable: bool
    rules: SiteRules
    deny: list[SiteDenyPattern] = Field(..., max_length=64)
    people: list[SiteWorkspacePerson] = Field(..., max_length=256)


class SiteAccessSet(BaseModel):
    """
    A local server's list. Eugene's file server is granted per workspace (`workspace.people`).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    people: list[SitePersonTools] = Field(..., max_length=256)


class SiteAuditEntry(BaseModel):
    """
    One line of the site's own audit log, kept on the machine and read by
    its owner (J8). It records who asked for what and what the site decided,
    never a file's contents or a tool's result. Since 2b.3b (J80) each line
    belongs to one person, who alone reads it through the root: a call or
    change in a workspace, to its holder; one about a person's own keys, to
    them; the rest (the local servers, sharing, settings, and anything not
    yet tied to a workspace), to the site's owner.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    at: AwareDatetime
    subject: str = Field(..., max_length=64)
    kind: SiteAuditKind
    server: str | None = Field(None, max_length=40)
    method: str | None = Field(None, max_length=64)
    tool: str | None = Field(None, max_length=128)
    action: str | None = Field(None, max_length=64)
    arguments: str | None = Field(
        None,
        description="The call's arguments as JSON, cut at 1,024 characters, with a write's text left out.",
        max_length=1024,
    )
    decision: SiteAuditDecision
    outcome: SiteAnswerStatus | None = None
    reason: str | None = Field(None, max_length=1024)
    rule: SiteDecision | None = Field(
        None, description='For a tool call since 2b.3b, the rule that applied (J72).'
    )
    asked: bool | None = Field(
        None,
        description='For a tool call under an `ask` rule, whether the call said the person\napproved it. Claimed, not checked, until person-held call signatures\n(J14b).\n',
    )


class SiteAccess(BaseModel):
    """
    Who may use which tools of one local server. Eugene's file server is
    granted per folder instead (`SiteFolder.people`, J6g).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ...,
        description="A person's id. Never `operator`; Eugene's owner reaches a site only through `ownerInDevMode`.",
        max_length=64,
        min_length=1,
    )
    server: str = Field(
        ...,
        description="A server on the machine. `files` is Eugene's own file server, one per\nmachine, whose tools take a `folder` argument (J6g). Any other id is one\na machine administrator gave a local server when adding it at the\nmachine; no local server's id begins `files`.\n",
        max_length=40,
        pattern='^(files|[a-z][a-z0-9-]{0,39})$',
    )
    tools: list[SiteToolGrant] = Field(..., max_length=64)


class SiteWorkspace(BaseModel):
    """
    A workspace, as the site reports it in each poll (2b.3b): a folder on the
    machine that one linked person, its holder, works in through the file
    server (J69). Its id and name, never its path (J76): the holder reads the
    path live (`workspace.list`). The root shows each person only their own,
    and the people the owner shared theirs with only the ones shared.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-f0-9]{32}$')
    name: str = Field(
        ...,
        description="The name its holder gave it, unique among the holder's own. Each\nperson's `folder` argument names their view: their own workspaces,\nthen those the owner shared with them, in the order reported, and a\nname already taken there, ignoring case, reads `Name (2)`. The root\nnames a person's view the same way, so its names match the site's.\n",
        max_length=96,
        min_length=1,
    )
    holder: str = Field(
        ...,
        description='The linked person it belongs to, whose own account opens it.',
        max_length=64,
        min_length=1,
    )
    writable: bool = Field(
        ...,
        description='Registered for changing files at all. When false, every `change` rule in it reads `deny`.',
    )
    rules: SiteRules
    people: list[SiteWorkspacePerson] | None = Field(
        None,
        description="For the site owner's workspaces, whom they shared it with (J69). Empty otherwise.",
        max_length=256,
    )


class SiteOperation(BaseModel):
    """
    What a site claims (`POST /v1/sites/operations/{id}/claim`): one
    operation, bound to this site's enrollment, to be done before
    `expiresAt`. The site host refuses one whose `site` or `enrolledAt` is
    not its own, so an operation queued for an earlier enrollment never runs
    on a later one; then its policy decides (J8).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., max_length=128, min_length=1)
    expiresAt: float = Field(..., description='Unix seconds. At most 30 s ahead.')
    site: str = Field(
        ...,
        description="A site's id: random, given by the root at enrollment, and fixed for\nthat enrollment. A machine that joins again gets a new one. Never a\nmachine's name, which is only its `label`.\n",
        pattern='^s-[a-z2-7]{26}$',
    )
    enrolledAt: AwareDatetime
    subject: str = Field(
        ...,
        description="Who asked, as the root established it (a person's id, or `operator` for Eugene's owner).",
        max_length=64,
        min_length=1,
    )
    kind: SiteOperationKind
    server: SiteServerId | None = Field(
        None, description="For `mcp`, the site's server."
    )
    request: McpRequest | None = Field(None, description='For `mcp`, the request.')
    grants: list[SiteGrantHint] | None = Field(
        None,
        description="For `mcp` to the file server from Eugene's owner, their dev-mode grants (J6e). Empty otherwise.",
        max_length=64,
    )
    asked: bool | None = Field(
        False,
        description="For `mcp`, Workbench's word that the person approved this call (`SiteCall.asked`, J72).",
    )
    action: str | None = Field(None, description='For `manage`, the action.')
    arguments: dict[str, Any] | None = Field(
        None, description='For `manage`, its arguments.'
    )
    names: dict[str, Any] | None = Field(
        None,
        description="For `manage`, how the root names each person the arguments name, by\nid. Display only: a site shows them on a held change marked as the\nroot's names (J54), and decides nothing by them.\n",
    )
    installMode: InstallModeName


class SiteAccountLink(BaseModel):
    """
    One link in the links file: *this Eugene person is this OS account on
    this machine* (§2.2, J27). Made at the machine only, by the machine's
    privileged starter (the agent on a Windows service install, root on a
    Linux system install, the join on a per-user install), never by the root
    or the site host.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(
        ..., description="The person's id.", max_length=64, min_length=1
    )
    name: str | None = Field(
        None, description='How the person signs in, for display.', max_length=256
    )
    account: str = Field(
        ...,
        description="The OS account's SID on Windows, or its uid in decimal elsewhere. Compared exactly.",
        max_length=256,
        min_length=1,
    )
    accountName: str = Field(..., max_length=256, min_length=1)
    linkedAt: AwareDatetime
    keys: list[SitePersonKey] | None = Field(
        [],
        description="The person's own keys, pinned at the machine (J14a,\n`person-held-keys.md` §4.1). The site checks every change this\nperson approves against them, never the person the root names.\n",
        max_length=8,
        validate_default=True,
    )


class SiteHeldList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., max_length=64)
    keys: list[Key] = Field(
        ...,
        description='The ids of the keys pinned to this person, at the machine and as passkeys.',
        max_length=16,
    )
    passkeys: list[SitePasskey] | None = Field(
        None,
        description='Their passkeys (J14a.3), for Workbench to choose which one signs.',
        max_length=8,
    )
    state: SiteSigningState | None = Field(
        None,
        description="The site's state for its owner; since 2b.3b, for anyone, the state of their own rules (`SitePersonLink.signing`).",
    )
    items: list[SiteHeldEdit] = Field(..., max_length=64)


class SiteWorkspaceList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    workspaces: list[SiteWorkspaceDetail] = Field(..., max_length=64)


class SiteAuditPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entries: list[SiteAuditEntry] = Field(..., max_length=200)


class SiteSummary(BaseModel):
    """
    What a job site holds, as the site itself reports it in each poll. The
    root keeps it as a cache: it answers Workbench's listings from it, and
    the site checks every call against its own copy again (rule 2 of §3.3).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    owner: str = Field(
        ...,
        description='The person the site pinned as its owner at its join.',
        max_length=64,
        min_length=1,
    )
    ownerInDevMode: bool = Field(
        ...,
        description="The site's owner lets Eugene's owner in while Eugene is in dev mode (J6e).",
    )
    folders: list[SiteFolder] | None = Field(
        None,
        description='From a site before 2b.3b, which reports folders with their paths. A newer site reports `workspaces` instead.',
        max_length=64,
    )
    workspaces: list[SiteWorkspace] | None = Field(
        None,
        description="Every linked person's workspaces, by id and name, never path (2b.3b, J76). The root shows each person only their own and those shared with them.",
        max_length=512,
    )
    servers: list[SiteServer] = Field(..., max_length=96)
    access: list[SiteAccess] = Field(
        ...,
        description="Who may use the local servers' tools. Folders carry their own people.",
        max_length=2048,
    )
    links: list[SitePersonLink] | None = Field(
        None,
        description="The people linked to an OS account on this machine (§2.2, J27), and\nwhether each one's worker is connected now. A linked person's calls\nrun as their own account; anyone else's run in the owner's worker,\nas the owner, confined to the folder (J27).\n",
        max_length=256,
    )
    linkPage: str | None = Field(
        None,
        description="Where a person links their account, on the machine itself: the\nagent's loopback link page on a Windows service install. Null where\nlinking is the elevated one-liner (a Linux system install, J36) or\nwhere only the installing person is served (a per-user install, J38).\n",
        max_length=256,
    )
    sharing: bool | None = Field(
        None,
        description='Whether this site can serve anyone but its owner. False on macOS,\nwhich has no folder boundary yet (§2.6). Absent means true.\n',
    )
    signing: SiteSigning | None = None


class SiteLinkFile(BaseModel):
    """
    The links file (§3.2): written by the machine's privileged starter,
    read by the site host, which cannot write it. One link per person, and
    one person per account.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    version: Literal[1]
    links: list[SiteAccountLink] = Field(..., max_length=256)


class SiteReport(BaseModel):
    """
    What a site host reports in each poll (`POST /v1/sites/poll`). The root
    keeps it as a cache for listings; the site checks every call against
    its own copy again (rule 2 of remote-nodes.md §3.3).

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: SiteHostProtocol
    hostVersion: str | None = Field(None, max_length=64)
    ready: bool
    reason: str | None = Field(None, max_length=1024)
    account: str | None = Field(
        None,
        description="The kind of OS account the site host itself runs in. Since 2b.2 the\nsite's tools run in each person's worker, as `SiteSummary.links`\nsays, and never in this account.\n",
        max_length=256,
    )
    site: SiteSummary | None = None
